modLoader = "javafml"
loaderVersion = "[34,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/PackagedAstral/issues"

[[mods]]
	modId = "packagedastral"
	version = "0@VERSION@"
	displayName = "PackagedAstral"
	description = "A PackagedAuto addon that adds Astral Sorcery autocrafting."
	logoFile = "packagedastral.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/packagedastral"

[[dependencies.packagedastral]]
	modId = "forge"
	versionRange = "[34,)"
	mandatory = true

[[dependencies.packagedastral]]
	modId = "packagedauto"
	versionRange = "[2.0.6,)"
	mandatory = true

[[dependencies.packagedastral]]
	modId = "astralsorcery"
	versionRange = "[1.16,)"
	mandatory = true
